### ISSUE TITLE
How to create project with .NET 5.x

### ISSUE THREAD

**Issue by wuwo1952368901** [NetCoreTemplates/web#1]
The projects created now use .NET 6. How to create projects using .NET 5?

**Comment by mythz** [comment]
You can browse each release in [/web/releases](https://github.com/NetCoreTemplates/web/releases) to find where `.csproj` still uses .NET 5.0 which is [/v27](https://github.com/NetCoreTemplates/web/tree/v27).

That you can then use to create a new project using the URL of its **.zip** archive:

```bash
$ mkdir ProjectName && cd ProjectName 
$ x new https://github.com/NetCoreTemplates/web/archive/refs/tags/v27.zip
```

Alternatively you can just download **v27** release Source Code zip archive:
https://github.com/NetCoreTemplates/web/archive/refs/tags/v27.zip

**Comment by mythz** [comment]
As this seems to be something many customers want to be able to do we've added support for it on our start page:

### [servicestack.net/start?tag=net5](https://servicestack.net/start?tag=net5)

And added docs for creating older versions of project templates: https://docs.servicestack.net/dotnet-new#creating-new-net-5-projects
